import type { Metadata } from "next";

import "www/styles/globals.css";

import { geistMono, geistSans } from "./font";
import { Toaster } from "www/components/ui/toaster";
import { AuthProvider } from "www/wrapper/auth-provider";
import { AuthApiService } from "www/external/api";
import { cookies, headers } from "next/headers";
import { ThemeProvider } from "www/wrapper/theme-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// async function getUser() {

// 	const headersList =await headers();
// 	console.log(headersList.get('session_id'))
// 	const response = await fetch(`${process.env.NEXT_PUBLIC_API}/api/auth/user`, {
// 		headers: {
// 			cookie: headersList.get("session_id") ?? "",
// 		},
// 	});
// 	if (!response.ok) return null;
// 	return response.json();
// }
export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<AuthProvider initialUser={null}>
						{children}
						<Toaster />
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
