// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
	GEMINI_API: string;
	REDDIT_CLIENT_ID:string;
	REDDIT_CLIENT_SECRET:string;
	REDDIT_ACCESS_TOKEN:string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	FRONTEND_URL: string;
}
